### PR TITLE
Depend on enum34 using PEP 508 environment markers

### PR DESCRIPTION
**Pull request by dsevero**
@jstasiak 

This package doesn't work with Poetry and other package managers that adhere to the new `pyproject.toml`  file. The reasons why are stated in #3.

```
The recommended way to specify dependencies specific to a python
version is to use environment markers.
```

This problem is happening everywhere in the python world. For example, see:

https://github.com/numba/llvmlite/commit/2aab7f4ba0fd7f6323aa305752644da382933366

### CODE REVIEW

**Comment by jstasiak** [comment]
Yeah, the thing is I didn't know a thing about environment markers when I made this so this whole package should be nuked really. I'll accept and release this regardless just so we have this done right, thanks!

**Comment by dsevero** [comment]
The idea is good.

This way, we just solved the issue for 1.5k+ packages :dancer: 

Cheers.

**Comment by eandersson** [comment]
This broke my installation at least.
> error in enum-compat setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in enum34; python_version < "3.4" at ; python_version < "3.4"

Yea confirmed just breaks in older versions of setuptools.

**Comment by dsevero** [comment]
@eandersson best solution would be to update `setuptools` with `pip install setuptools -U`

**Pull request merged**
